version: '3.8'

services:
  db:
    container_name: db
    build: ./db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: kintai_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "3306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d # テーブル作成
      - ./db/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログ保存
    networks:
      - local-net

  backend:
    container_name: backend
    links:
      - db
    build: ./backend
    volumes:
    - ./backend/dockervenv:/src/.venv
    - ./backend:/src
    ports:
    - "8000:8000"
    tty: true
    init: true
    # depends_on:
    # - db
    # environment:
    #   DATABASE_URL: "mysql://root:your_password@db/kintai_db"
    networks:
      - local-net

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - nuxt_node_modules:/app/node_modules
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      HOST: 0.0.0.0
      port: 80
      CHOKIDAR_USEPOLLING: true
    command: sh -c "yarn && yarn dev"
volumes:
  nuxt_node_modules:
# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge