version: '3.8'

services:
  db:
    container_name: db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: kintai_db
    ports:
    - "3306:3306"

  backend:
    container_name: backend
    build: ./backend
    volumes:
    - ./backend/dockervenv:/src/.venv
    - ./backend:/src
    ports:
    - "8131:8131"
    tty: true
    init: true
    depends_on:
    - db
    environment:
      DATABASE_URL: "mysql://root:your_password@db/kintai_db"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - nuxt_node_modules:/app/node_modules
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      HOST: 0.0.0.0
      port: 80
      CHOKIDAR_USEPOLLING: true
    # command: sh -c "npm && npm run dev"
volumes:
  nuxt_node_modules: