FROM mariadb:11.4
# MySQLの操作ログのファイルを作成
# RUN touch /var/log/mysql/mysqld.log

ENV MARIADB_HOST=mysql
ENV MARIADB_DATABASE=kintai_db
ENV MARIADB_ROOT_PASSWORD=root
ENV MARIADB_USER=admin
ENV MARIADB_PASSWORD=password

EXPOSE 3306