FROM mysql:latest
# MySQLの操作ログのファイルを作成
# RUN touch /var/log/mysql/mysqld.log

ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=kintai_db
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=password

EXPOSE 3306